from brogard/seq_base

ENTRYPOINT      ["python", "train.py", "-d", "../../var/data/ml-1m/", "-m", "RNN", "--r_t", "LSTM", "--r_l", "20",  "--r_act_o", "rectify", "--r_act_i", "rectify", "--r_act_f", "rectify", "--save", "All", "--max_iter", "524288", "--dir"]
